//: [Next](@next)
//: # With a tortoise 🐢
//: [👉 With 2 tortoises 🐢🐢](@next)
import PlaygroundSupport
import TortoiseGraphics
import CoreGraphics
let myFrame = CGRect(x: 0, y: 0, width: 500, height: 500)
let canvas =
    PlaygroundCanvas(frame:myFrame )
canvas.frameRate = 100
canvas.color = .white
PlaygroundPage.current.liveView = canvas

canvas.drawing { turtle in
    // Draw a square
    for _ in 1...2{
        turtle.goto(0, 0)
        turtle.penUp()
        turtle.forward(250)
        turtle.penDown()
        turtle.left(180)
        turtle.forward(500)
        turtle.penUp()
        turtle.left(180)
        turtle.forward(250)
        turtle.penUp()
        turtle.right(90)
        turtle.forward(250)
        turtle.penDown()
        turtle.left(180)
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(0, 50)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(0, 100)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(0, 150)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(0, 200)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(0,250)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(0, -50)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(0, -100)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(0, -150)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(0, -200)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(0, -250)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(-50,0)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(-100,0)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(-150, 0)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(-200, 0)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(-250, 0)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(50, 0)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(100,0)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(150,0)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(200,0)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
        turtle.goto(250,0)
        turtle.left(90)
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.right(90)
        turtle.penUp()
        turtle.forward(250)
        turtle.left(180)
        turtle.penDown()
        turtle.forward(500)
        turtle.penUp()
       
    }
}





